### ISSUE TITLE
I Need help with node modules (MV)

### ISSUE THREAD

**Issue by ksaOfficial** [00due/Discord-RPC-for-RMMZ#2] opened 2023-08-10 19:08 UTC
ok i can't figure out where should i put my node module folder? like is it the game's Executable or is it the master executable???

Like i need to understand what should i do at exporting at MV?

**Comment by 00due** [comment] 2023-08-11 04:06
On MV it's a bit complicated.
When you're playtesting, it should be in your project's directory (the one where you have the game.rpgproject and the folders audio, data, js etc.

After you export the game, MV moves the project project's directory to the `www/` folder. The game does not recognize the modules there, so you'll have to move the `node_modules` folder to the folder where your *game's* executable is (typically `game.exe`)

**Comment by ksaOfficial** [comment] 2023-08-11 07:43
Ok i got an error where it says here 'replaceRow1' Undefined

![Screenshot_103](https://github.com/00due/Discord-RPC-for-RMMZ/assets/53649942/a5943307-eedc-427a-a171-35fac35c9e1a)

is it because i made plugins order wrong?

or is it because i put the node modules at www or at my game's project?
here is where i put the www and moved it to my game's project:
![Screenshot_104](https://github.com/00due/Discord-RPC-for-RMMZ/assets/53649942/bff80d93-504b-4817-8514-e625e7af2cea)
![Screenshot_105](https://github.com/00due/Discord-RPC-for-RMMZ/assets/53649942/af5bdbc1-4efa-4692-9826-caff2b07c5b9)

**Comment by 00due** [comment] 2023-08-11 08:52
That's weird...

That's definitely an error caused by the plugin, not the node_modules. Can you try changing the plugin to top of the list or to the bottom of the list, or even temporarily disabling other plugins to see if there's a compatibility issue with another plugin?

**Comment by ksaOfficial** [comment] 2023-08-11 09:28
ok i did changed the plugins order, still not working.

also its still not defined and even i added 'replaceRow 1 "something something"' it still not defined replaceRow1
![Screenshot_106](https://github.com/00due/Discord-RPC-for-RMMZ/assets/53649942/fbda8887-5ed0-40de-9f02-e95a2d136ee5)

even in discord, i can't see my game is popping in my profile. also i can't know if the plugin doesn't work? i did put the right discord application id and everything

**Comment by 00due** [comment] 2023-08-11 12:01
That is very weird, since it was working just fine on another project.

Even though the error says "replaceRow1 is not defined", it definitely is. I've checked it multiple times for possible typos and other mistakes, but didn't find anything.

Can you try opening the debug console (F8) when this error occurs to see if there's something more there?

**Comment by ksaOfficial** [comment] 2023-08-12 04:51
ok hello, hi, uhh i looked into it so here is the result
![Screenshot_108](https://github.com/00due/Discord-RPC-for-RMMZ/assets/53649942/ad21344f-cac8-4752-a3a6-425dea574796)
![Screenshot_109](https://github.com/00due/Discord-RPC-for-RMMZ/assets/53649942/fd3040ef-7c35-4a4d-bd05-89ecd900c398)

**Comment by 00due** [comment] 2023-08-12 17:09
Closing this as issue is caused by using older nwjs and can't be fixed. A solution is to update nwjs yourself.

Commit 27dd746 adds a link to a guide that explains how to update nwjs.

**Closed as completed by 00due** 2023-08-12 17:09 UTC
Labels: bug, MV
